apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: demo-error-1 
  janus-idp.io/tekton: demo-error-1
  backstage.io/kubernetes-id: demo-error-1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: demo-error-1
resources: 
- application-dev.yaml