---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: demo-error-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-error-1 
  name: demo-error-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi